version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/my-app
hooks:
  BeforeInstall:
    - location: scripts/install_docker.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/pull_image.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: ubuntu