version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/my-app
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 600
      runas: root
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 600
      runas: ubuntu