version: '3.8'

services:
  app:
    image: 443526375408.dkr.ecr.eu-north-1.amazonaws.com/devops-app:latest
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'