name: CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Login to Docker Hub
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            
            # Navigiere in das Anwendungsverzeichnis
            mkdir -p /home/erik_sim/my-app
            cd /home/erik_sim/my-app

            # Lade die docker-compose.yml von deinem GitHub-Repo herunter
            curl -o docker-compose.yml https://raw.githubusercontent.com/BetaCom16/DevOpsUIProject/main/docker-compose.yml

            # Ziehe das neueste Image und starte die Anwendung
            docker-compose pull
            docker-compose up -d